version: "3"
services:
  app:
    container_name: tracker_express
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./app:/app
    links:
      - mongo
  mongo:
    container_name: tracker_mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
